name: expense_splitter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.21.3+1
  get_it: ^8.2.0
  go_router: ^16.2.0
  google_sign_in: ^7.1.1
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  mongo_dart: ^0.10.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
